/*   Error and other messages related to the GELD library.
/*
msg err1
  lan english -def
    Invalid meter multipliers file header line.  The first three fields
    must be "METER ID", "RATE", and "MULTIPLIER", case-insensitive.
msg err2
  lan english -def
    Bad meter ID on line %2 of file "%1s".
msg err3
  lan english -def
    Error reading rate class code on line %2 of file "%1s".
msg err4
  lan english -def
    Invalid rate class code on line %2 of file "%1s".
msg err5
  lan english -def
    Bad meter multiplier on line %2 of file "%1s".
msg err6
  lan english -def
    Attempt to set rate class for a meter with a different rate class
    previously set.  New rate class encountered on line %2 of file "%1s".
